---
dist: xenial
sudo: required

language: ruby
cache: bundler

before_script: sudo apt-get update -y && make ubuntu-packages prepare

script: make build-all

notifications:
  email:
    on_success: never
    on_failure: never
